# NetBackup 8.0 Installation
# # ==========================
# # Author F. Buirey
# # Date: 03/21/2017
# # Version: 1.0
# # Purposes: umount NFS File system containing NBU Sources
# #
#
---
- name: Set PATH
  template:
    src: netbackup.sh
    backup: yes
    dest: /etc/profile.d/netbackup.sh
    owner: root
    group: root
    mode: 0644

