# NetBackup 8.0 Installation
# # ==========================
# # Author F. Buirey
# # Date: 03/21/2017
# # Version: 1.0
# # Purposes: Setup Kernel Parameters for Install
# #
#
---
- name: Set nofile soft limit a least to 10 0000
  pam_limits:
    domain: root
    limit_item: nofile
    limit_type: soft
    value: 10000
    use_max: yes

- name: Set nofile hard limit a least to 10 0000
  pam_limits:
    domain: root
    limit_item: nofile
    limit_type: hard
    value: 10000
    use_max: yes
  when: (ansible_distribution == "CentOS") or (ansible_distribution == "RedHat")

- name: Set Semaphore Value
  sysctl:
    name: kernel.sem
    value: 300 307200 32 1024
  when: (ansible_distribution == "CentOS") or (ansible_distribution == "RedHat")

