# NetBackup 8.0 Installation
# # ==========================
# # Author F. Buirey
# # Date: 03/21/2017
# # Version: 1.0
# # Purposes: Disable SELinux and Firewal for Netbackup
# #
---
- name: Disable SElinux
  selinux:
    state: disabled

- name: Stop Firewalld service
  service:
    name: firewalld
    state: stopped
    enabled: no
  when: (ansible_distribution == "CentOS")  and (ansible_distribution_major_version == "7")

- name: Stop Iptables service
  service:
    name: iptables
    state: stopped
    enabled: no
  when: (ansible_distribution == "CentOS") and (ansible_distribution_major_version == "6")

