---
- hosts: nbuclient
  vars:
    nfs_server: 192.168.1.250
    nfs_share: /sources
    install_path: /sources/NetBackup_8.0_CLIENTS2/
    licence: 'xxxx-xxxx-xxxx-xxxx-xxxx-xxxx-xxxx-xx'
    masterserver: 'netbackup.buirey.local'
    clientname: 'mycms.buirey.local'

# Do you wish to continue? [y,n] (y)
# Do you want to install the NetBackup client software for this client? [y,n] (y)
# Enter the name of the NetBackup master server : 
# Would you like to use "mycms" as the configured name of the NetBackup client? [y,n] (y)
# Enter the name of this NetBackup client :
# 

    - name: Install netbackup Client
      shell: |
        ./install <<EOF
        y
        y
        {{masterserver}}
        n
        {{clientname}}

        EOF
      args:
        chdir: /sources/NetBackup_8.0_CLIENTS2/
      register: install_nbu
      failed_when: install_nbu.rc!=0
      when: (ansible_system=="Linux")
